# Generated by Django 4.1.7 on 2023-03-31 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_order_paid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
