# Generated by Django 4.1.7 on 2023-04-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_product_discount_product_discounted_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
