# Generated by Django 4.1.7 on 2023-04-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_orderitem_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='item_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
