# Generated by Django 4.1.7 on 2023-04-09 07:54

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='product/'),
        ),
    ]
